// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9VlogsrpzflivmJwNHj8Ea6KH3Lh_un4',
    appId: '1:138885047261:web:a1f3f39a0ce05b6530cc34',
    messagingSenderId: '138885047261',
    projectId: 'les-mind',
    authDomain: 'les-mind.firebaseapp.com',
    databaseURL: 'https://les-mind-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'les-mind.appspot.com',
    measurementId: 'G-B701LXBKDF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDA_CAUWHZ5x5RWDnuLnqXivjBKFx6SkB8',
    appId: '1:138885047261:android:948ee1bfd7587c4e30cc34',
    messagingSenderId: '138885047261',
    projectId: 'les-mind',
    databaseURL: 'https://les-mind-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'les-mind.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7sd8whrA4Kyl48hqcWJDmkLJPOFS7Sxg',
    appId: '1:138885047261:ios:1e194d0f988f530f30cc34',
    messagingSenderId: '138885047261',
    projectId: 'les-mind',
    databaseURL: 'https://les-mind-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'les-mind.appspot.com',
    iosClientId: '138885047261-siijv9hvdo58fi0d48csnnbui3fkftq1.apps.googleusercontent.com',
    iosBundleId: 'com.example.first',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA7sd8whrA4Kyl48hqcWJDmkLJPOFS7Sxg',
    appId: '1:138885047261:ios:1e194d0f988f530f30cc34',
    messagingSenderId: '138885047261',
    projectId: 'les-mind',
    databaseURL: 'https://les-mind-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'les-mind.appspot.com',
    iosClientId: '138885047261-siijv9hvdo58fi0d48csnnbui3fkftq1.apps.googleusercontent.com',
    iosBundleId: 'com.example.first',
  );
}
